2020-12-07 13:23:07,623 INFO    MainThread:10554 [wandb_setup.py:_flush():68] setting env: {}
2020-12-07 13:23:07,623 INFO    MainThread:10554 [wandb_setup.py:_flush():68] multiprocessing start_methods=fork,spawn,forkserver
2020-12-07 13:23:07,623 INFO    MainThread:10554 [wandb_setup.py:_flush():68] setting login settings: {}
2020-12-07 13:23:07,623 INFO    MainThread:10554 [wandb_init.py:_log_setup():302] Logging user logs to /home/syseo/workspace/FIVO_Gumbel/wandb/run-20201207_132307-pezenhoa/logs/debug.log
2020-12-07 13:23:07,624 INFO    MainThread:10554 [wandb_init.py:_log_setup():303] Logging internal logs to /home/syseo/workspace/FIVO_Gumbel/wandb/run-20201207_132307-pezenhoa/logs/debug-internal.log
2020-12-07 13:23:08,787 INFO    MainThread:10554 [wandb_run.py:_console_start():1213] atexit reg
2020-12-07 13:23:08,788 INFO    MainThread:10554 [wandb_run.py:_redirect():1083] redirect: SettingsConsole.REDIRECT
2020-12-07 13:23:08,789 INFO    MainThread:10554 [wandb_run.py:_redirect():1086] Redirecting console.
2020-12-07 13:23:08,789 INFO    MainThread:10554 [redirect.py:install():204] install start
2020-12-07 13:23:08,789 INFO    MainThread:10554 [redirect.py:install():219] install stop
2020-12-07 13:23:08,789 INFO    MainThread:10554 [redirect.py:install():204] install start
2020-12-07 13:23:08,789 INFO    MainThread:10554 [redirect.py:install():219] install stop
2020-12-07 13:23:08,789 INFO    MainThread:10554 [wandb_run.py:_redirect():1130] Redirects installed.
2020-12-07 13:23:08,996 INFO    MainThread:10554 [wandb_watch.py:watch():33] Watching
2020-12-07 13:23:09,009 INFO    MainThread:10554 [wandb_run.py:_atexit_cleanup():1186] got exitcode: 1
2020-12-07 13:23:09,009 INFO    MainThread:10554 [wandb_run.py:_restore():1158] restore
2020-12-07 13:23:09,010 INFO    MainThread:10554 [redirect.py:uninstall():223] uninstall start
2020-12-07 13:23:09,010 INFO    MainThread:10554 [redirect.py:_stop():278] _stop: stdout
2020-12-07 13:23:09,010 INFO    stdout    :10554 [redirect.py:_pipe_relay():120] relay done saw last write: stdout
2020-12-07 13:23:09,010 INFO    stdout    :10554 [redirect.py:_pipe_relay():136] relay done done: stdout
2020-12-07 13:23:09,011 INFO    MainThread:10554 [redirect.py:_stop():284] _stop closed: stdout
2020-12-07 13:23:09,011 INFO    MainThread:10554 [redirect.py:_stop():290] _stop joined: stdout
2020-12-07 13:23:09,011 INFO    MainThread:10554 [redirect.py:_stop():292] _stop rd closed: stdout
2020-12-07 13:23:09,011 INFO    MainThread:10554 [redirect.py:uninstall():227] uninstall done
2020-12-07 13:23:09,011 INFO    MainThread:10554 [redirect.py:uninstall():223] uninstall start
2020-12-07 13:23:09,011 INFO    MainThread:10554 [redirect.py:_stop():278] _stop: stderr
2020-12-07 13:23:09,011 INFO    MainThread:10554 [redirect.py:_stop():284] _stop closed: stderr
2020-12-07 13:23:09,011 INFO    stderr    :10554 [redirect.py:_pipe_relay():120] relay done saw last write: stderr
2020-12-07 13:23:09,011 INFO    stderr    :10554 [redirect.py:_pipe_relay():136] relay done done: stderr
2020-12-07 13:23:09,011 INFO    MainThread:10554 [redirect.py:_stop():290] _stop joined: stderr
2020-12-07 13:23:09,011 INFO    MainThread:10554 [redirect.py:_stop():292] _stop rd closed: stderr
2020-12-07 13:23:09,011 INFO    MainThread:10554 [redirect.py:uninstall():227] uninstall done
2020-12-07 13:23:09,124 INFO    MainThread:10554 [wandb_run.py:_wait_for_finish():1300] got exit ret: uuid: "eadfb7380b704691808ad40abec0ad79"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 1
    }
    pusher_stats {
      total_bytes: 686
    }
  }
}

2020-12-07 13:23:11,134 INFO    MainThread:10554 [wandb_run.py:_wait_for_finish():1300] got exit ret: uuid: "ae7cc5cf6763401784427ae733541e72"
response {
  poll_exit_response {
    done: true
    exit_result {
    }
    file_counts {
      wandb_count: 5
    }
    pusher_stats {
      uploaded_bytes: 4083
      total_bytes: 4083
    }
  }
}

2020-12-07 13:23:12,220 INFO    MainThread:10554 [wandb_run.py:_show_files():1509] logging synced files
2020-12-07 13:23:12,222 INFO    MainThread:10554 [internal.py:handle_exit():138] Internal process exited
