Traceback (most recent call last):
  File "train.py", line 148, in <module>
    train(epoch)
  File "train.py", line 34, in train
    kld_loss, nll_loss, _, _ = model(data)
  File "/home/syseo/anaconda3/envs/jericho/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/syseo/workspace/FIVO_Gumbel/model.py", line 115, in forward
    phi_z_t = self.phi_z(z_t)
NameError: name 'z_t' is not defined
